# config/_default/config.toml

baseURL = "https://codenotfound.com"
languageCode = "en"

paginate = 6
timeout = 60000
ignoreFiles = ['\.svg$']

[imaging]
  quality = 75
  resampleFilter = "MitchellNetravali"

googleAnalytics = "G-SY723D2W58"
