# config/_default/config.toml

baseURL = "https://cnf-sites.github.io/cnf-blog-congo"
languageCode = "en"

paginate = 6
timeout = 60000
ignoreFiles = ['\.svg$']

[imaging]
  quality = 75
  resampleFilter = 'MitchellNetravali'
