# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Tutorials"
  pageRef = "tutorials"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[footer]]
  name = "Terms of Service"
  pageRef = "terms-of-service"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy-policy"
  weight = 20

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 40
