# config/_default/params.toml

colorScheme = "congo"
defaultAppearance = "light"

enableCodeCopy = true

contactFormdId = "xrgjjnrr"

[footer]
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true

[article]
  showDate = false
  showDateUpdated = true
  showAuthor = false
  showBreadcrumbs = false
  showTableOfContents = true
  showComments = true
  sharingLinks = ["facebook", "twitter", "reddit", "linkedin"]

[list]
  showSummary = true
  groupByYear = false

[verification]
  google = "77J2Ogma8Na_Ois1-6-dneKGorijKqv2JV2tHwpp6Mw"
  bing = ""
